### PR TITLE
Add GitHub action for make and deploy docs

### PR DESCRIPTION
**Pull request by jondea**
It needs a bit of polish, but it should get the ball rolling. I added an option to autogen so that I didn't need to build all of oomph-lib to build the docs.

### CODE REVIEW

**Comment by jondea** [comment]
Link to build https://github.com/jondea/oomph-lib/actions/runs/1006069895

**Comment by PuneetMatharu** [comment]
I'm not entirely sure what the deployment does (but that's likely me just being silly!). Is there a way for me, personally, to view the site after it's been deployed via the GitHub action? Is the build/ folder something that's just only built locally and discarded after the GitHub Action completes? Or, more specifically, how do I check myself to make sure this works as expected?

**Comment by jondea** [comment]
Deployment currently means pushing to the gh-pages branch of the repo where the action runs, so in this example the raw source is here https://github.com/jondea/oomph-lib/tree/gh-pages

To get that actually displaying as a website, you have a few options:
1. Use GitHub to host. Select the gh-pages branch as your "page" in the repo settings on GitHub, that then causes it to appear on your personal github.io account (although it does take a few hours to load). You can see this on my old repo here https://jondea.github.io/oomph-lib-old/doc/html/index.html This link should work at some point too for the new repo
https://jondea.github.io/oomph-lib/doc/html/index.html
2. You can self host. This would require either pulling the gh-page branch periodically, or changing the "deploy" part of the action to upload the content to your own web server.

**Comment by PuneetMatharu** [comment]
@MatthiasHeilManchester, happy with this? I am. If you're also happy, we can go ahead and merge it in. 

@jondea, are you happy for me to squash the commits into one for the merge? Or would you prefer to keep the history?

**Comment by jondea** [comment]
Ordinarily I'm against squashing, but given how much of a mess this branch is, squashing probably makes sense.

**Comment by PuneetMatharu** [comment]
Got it. Great work on this. I've gone ahead and merged the changes in now (and thanks for rebasing!).

**Pull request merged**
